version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "05:00"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "dependabot"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
