version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - ghcr
registries:
  ghcr:
    type: docker-registry
    url: ghcr.io
    username: ${{secrets.USERNAME}}
    password: ${{secrets.PASSWORD}}
