name: 'Probe Action'
description: 'Run probe workflow automation tool'
author: 'linyows'

inputs:
  path:
    description: 'Path to the workflow YAML file'
    required: false
  paths:
    description: 'Array of paths to the workflow YAML files'
    required: false
  version:
    description: 'Version of probe to use (default: latest)'
    required: false
    default: 'latest'
  options:
    description: 'Command line options for probe (e.g., "--verbose --rt")'
    required: false
    default: ''
  workdir:
    description: 'Working directory to change to before running probe'
    required: false
    default: ''
  action-debug:
    description: 'Enable action debug output (true/false/yes/1)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Download and run probe
      run: |
        # Determine paths to process
        PATHS=""
        if [ -n "${{ inputs.paths }}" ]; then
          # GitHub Actions passes multiline strings as-is
          PATHS="${{ inputs.paths }}"
        elif [ -n "${{ inputs.path }}" ]; then
          PATHS="${{ inputs.path }}"
        else
          echo "Error: Either 'path' or 'paths' input must be provided"
          exit 1
        fi
        
        # Set GITHUB_TOKEN environment variable for the script
        export GITHUB_TOKEN="${{ github.token }}"
        
        # Run the external script
        bash "${{ github.action_path }}/run.sh" "$PATHS" "${{ inputs.version }}" "${{ inputs.options }}" "${{ inputs.workdir }}" "${{ inputs.action-debug }}"
      shell: bash

branding:
  icon: 'activity'
  color: 'blue'
