name: Test Probe Action

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  test-basic:
    name: Test Basic HTTP Functionality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test basic HTTP with default settings
        uses: ./
        with:
          path: test/basic-http.yml

      - name: Test with verbose output
        uses: ./
        with:
          path: test/basic-http.yml
          options: '--verbose'

      - name: Test with action debug
        uses: ./
        with:
          path: test/basic-http.yml
          action-debug: true

  test-status-codes:
    name: Test Status Code Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test status code checking
        uses: ./
        with:
          path: test/status-check.yml
          options: '--verbose'

  test-probe-versions:
    name: Test Different Probe Versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        probe-version: ['latest', 'v0.20.1']
    steps:
      - uses: actions/checkout@v4

      - name: Test with probe ${{ matrix.probe-version }}
        uses: ./
        with:
          path: test/basic-http.yml
          version: ${{ matrix.probe-version }}

  test-platforms:
    name: Test Cross-Platform
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Test on ${{ matrix.os }}
        uses: ./
        with:
          path: test/basic-http.yml
          options: '--verbose'

  test-marketplace:
    name: Test Marketplace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test single workflow
        uses: linyows/probe-action@main
        with:
          path: test/basic-http.yml

      - name: Test multiple workflows
        uses: linyows/probe-action@main
        with:
          paths: |
            basic-http.yml
            status-check.yml
          workdir: ./test
          action-debug: true
